### ISSUE TITLE
Retroterm 0.20 flashing characters with Particles BBS

### ISSUE THREAD

**Issue by kiFlaFlaki** [retrocomputacion/retroterm#7]
When connected to particlasbbs.dyndns.org:6400 with Plus/4 I get flashing characters all the time. Text is normal but flashing. I did not tried on C64. Teleterm on Plus/4 works OK with Particles BBS. I am using WiFi User Port modem with ZiModem firmware.

**Comment by retrocomputacion** [comment]
I'll have to check exactly what is that ParticlesBBS is sending. The FLASHON/FLASHOFF characters codes are not used on the C64, a normal PETSCII BBS shouldnt be sending those codes.

I'll get back to you once I check it. If this is a problem with the BBS, and I found others that do the same I think an option for the user to disable/enable the flash codes on Retroterm would be the best solution.

**Comment by kiFlaFlaki** [comment]
I was surprised too, first time I see that kind of behavior of particles, I use that BBS on many retro platforms. No problems with various petscii supported terminal programs on C64/128, VIC20, Plus/4, Amiga.

**Comment by retrocomputacion** [comment]
Yes, is the BBS sending out those FLASHON codes, but I found out why: is the same code the C128 uses for turn the underline mode off in the 80 column screen.
Unfortunately the BBS sends that code not only at login but also each time the main menu is printed. Otherwise a quick workaround would be to get out of streaming mode by pressing '+++' then pressing CTRL + > and then going back to streaming mode with ATO

I'll be adding a key combination to toggle support for the FLASH codes, the same way C= + M toggles the sound

**Comment by retrocomputacion** [comment]
Please check in the code section there's a new file (rt_p4_v0.21.prg) in the build folder.
I have added a new key combo shortcut: CBM+,
This toggles support for the FLASHON control code and disables the flash attribute if currently on, this means if you have flashing characters on screen, and then you disable FLASHON with the key combo any further incoming text will not flash.

Let me know how it works for you.

**Comment by kiFlaFlaki** [comment]
I tested rt_p4_v0.21.prg and unfortunately it doesn't work. Tried CBM+ shortcut combination but no change for flashing. Any further text still keeps flashing. I tried many times with combo in different menus on Particles. CBM and + works ok, they are not broken.

**Comment by retrocomputacion** [comment]
Ah no sorry I wasn't clear, the key combo is CBM and the ',' key (the one that says Flash On on the front)

**Comment by kiFlaFlaki** [comment]
Great, thanks for clarification, tried CBM ,  combo, works perfectly now. Flashing stops for new characters after activating combo! Thanks!

**Comment by retrocomputacion** [comment]
Cool! I'm closing this then. Thanks for reporting this problem!
